const images = [
"https://drive.google.com/uc?export=view&id=1tqr28yUY34VOgHFjov52Ot1peGJVdiBJ",
"https://drive.google.com/uc?export=view&id=1w2VNORYwWx3FdxxoggeB3aoTLFqg_udF",
"https://drive.google.com/uc?export=view&id=1ytbjEHcMqWrh1pnukxJNaKambx_Sq-Pf",
"https://drive.google.com/uc?export=view&id=1k2uAT7zFhmTzPoGgchndOERiipg8pf_d",
"https://drive.google.com/uc?export=view&id=1p2aAELRr2YKW6y3VLmSWR-5AU9sCpll8",
"https://drive.google.com/uc?export=view&id=1pFHwSxwH8fSPRQxHc7Lhq5sO_1v2L8JO",
"https://drive.google.com/uc?export=view&id=1qkF4eXQ4hOipHic6pYoleGcW7C6QKdd3",
"https://drive.google.com/uc?export=view&id=1scYjOBZIaOdWEf5lT5YyaRPJM0wIvsAX",
"https://drive.google.com/uc?export=view&id=1dpsPO3IYNKnPiOUatc7DfVIB-fMMDwzx",
"https://drive.google.com/uc?export=view&id=1dr6OK18lXuoZDsGzJrShqWXarsDBl19w",
"https://drive.google.com/uc?export=view&id=1euLaq8GVW-LWdiv0dBWCvFwmSluDNUoC",
"https://drive.google.com/uc?export=view&id=1gGKYT03cD9uiGOAiNGRGiEdBfv6Ec6Ys",
"https://drive.google.com/uc?export=view&id=1hkX3Ren2k6V7eTSZI9Lk6o-bD7MxN9K5",
"https://drive.google.com/uc?export=view&id=1VMvR0KQ1f4L174VvRO5PYbLLxeGIskjx",
"https://drive.google.com/uc?export=view&id=1ZUOsSDPY0L4tMQhRMg3C2n_ef2yAw67G",
"https://drive.google.com/uc?export=view&id=1aPU6VZveyFohnVnHyo22FDI8fCHH_B0F",
"https://drive.google.com/uc?export=view&id=1aqmEleVjn8PkI1kLgbuFIM3p0uetRohN",
"https://drive.google.com/uc?export=view&id=1cDltVg04IQAPDKAmb9x16l9imZsoHSWM",
"https://drive.google.com/uc?export=view&id=1cZFLwrHdz36sotjgScPjiFWkFpR9Ujwu",
"https://drive.google.com/uc?export=view&id=1Qn-zMDLnFQ_wshGM0nJZ4NnHqMRp4KvB",
"https://drive.google.com/uc?export=view&id=1QpAh6xRfi6HpS550RgsAJtimIAt4WYW6",
"https://drive.google.com/uc?export=view&id=1SXtxkeaC4C7-3zv9BIF4j9Foq42TSLCR",
"https://drive.google.com/uc?export=view&id=1TdhLAzFT29PONVWeeRGIQEDIdj0cSC81",
"https://drive.google.com/uc?export=view&id=1VJGKn04J3jBU0pKIqzN5VQPBP79IcyIL",
"https://drive.google.com/uc?export=view&id=1OJF_nncalBfVcTIAlgiFa84QdxwMOiro",
"https://drive.google.com/uc?export=view&id=1OSwl7Nu5jP4FJOk77r5pPqi0VcwcmVdd",
"https://drive.google.com/uc?export=view&id=1OuqCeyb3x2mx8BYB1z7VBlp5eQPemXXJ",
"https://drive.google.com/uc?export=view&id=1OzP8yVpUUorjFuZd7GbKWDYCD7DWe2B-",
"https://drive.google.com/uc?export=view&id=1Pae_UV-ALYKmGxCOSBY0VHdCJAb85vKs",
"https://drive.google.com/uc?export=view&id=1HMJ_vEvfMMAyhZ6Vh5Nf1ZGaPZ8oKO4x",
"https://drive.google.com/uc?export=view&id=1I1QOa6DtuIjYJta85Q9cntNg9RdWPfWI",
"https://drive.google.com/uc?export=view&id=1I5uwbfKTA0-VQAksg9pJMVWLuw9VnG2_",
"https://drive.google.com/uc?export=view&id=1JCIthqjrjvKoSsPQunrWTa0qQ3PQOdk7",
"https://drive.google.com/uc?export=view&id=1Jw11fS0FQEQ7HqMH5xA8yXiRg400dsSc",
"https://drive.google.com/uc?export=view&id=1M4v1s5WRVGQh30El4WGN-3qpl6t2of_7",
"https://drive.google.com/uc?export=view&id=1Dziyk-64UkvSw3dxCaD6lDlnTXTG_Ppr",
"https://drive.google.com/uc?export=view&id=1EGmASenyi2uZbClP6DcSBI6EkyiBoWEm",
"https://drive.google.com/uc?export=view&id=1GDvipd_F0GfK2gicNk0X0foBe_8bPVLM",
"https://drive.google.com/uc?export=view&id=1HEjENuWhUYe6X1QtVEuSFiHfH86YExhv",
"https://drive.google.com/uc?export=view&id=1HIdML13R-ggipeCVxt6aL3u3spbsxIYH",
"https://drive.google.com/uc?export=view&id=12lehjNh3iZEEUOWa2i5FY0TVtiQ4N33Y",
"https://drive.google.com/uc?export=view&id=134VlDdy3RTfN0GRvTY1gUbM9qj-nRBDk",
"https://drive.google.com/uc?export=view&id=14vFDH9wO58wE_ylDYeD5ic7dg6LdAU0S",
"https://drive.google.com/uc?export=view&id=16hYeSlLszGHmBmVfAM3v1Fq2hx5L9VD8",
"https://drive.google.com/uc?export=view&id=18oCzkGhBz_0MfWZTCqxYdfUIeshCN_2Q",
"https://drive.google.com/uc?export=view&id=19DznfK9ikwTT96a1YDMsQtTvoPsdwEX2",
"https://drive.google.com/uc?export=view&id=1-5xU3DmqIR_CmQx9AeU5PqSjJX8Th8jz",
"https://drive.google.com/uc?export=view&id=1-Q2QKdP0LiSkDydeiC_ZiKj8THHjjyL5",
"https://drive.google.com/uc?export=view&id=10MoOh3KiOr1c2vvXj9QUubWjRMzCMl-Q",
"https://drive.google.com/uc?export=view&id=10igVkvKxYgU7OQ7c5GTeMcP7OXahwLpC",
"https://drive.google.com/uc?export=view&id=1eXaE5bgkPFEOfc76AzBJ6jUAnvFPXeEA"
];

// pick random image
const randomImage = images[Math.floor(Math.random() * images.length)];

// display it
document.getElementById("randomImage").src = randomImage;
